export const stats = [
  { value: 50000, suffix: "+", label: "Jobs Available" },
  { value: 5000, suffix: "+", label: "Verified Companies" },
  { value: 200000, suffix: "+", label: "Registered Candidates", display: "2,00,000+" },
  { value: 98, suffix: "%", label: "Placement Success" },
];

export const companies = [
  {
    id: "google",
    name: "Google",
    industry: "Technology",
    openJobs: 42,
    rating: 4.8,
    logo: "G",
    color: "#4285F4",
    location: "Bengaluru",
    description: "Organize the world's information and make it universally accessible.",
  },
  {
    id: "amazon",
    name: "Amazon",
    industry: "E-Commerce",
    openJobs: 67,
    rating: 4.5,
    logo: "A",
    color: "#FF9900",
    location: "Hyderabad",
    description: "Earth's most customer-centric company.",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    industry: "Technology",
    openJobs: 38,
    rating: 4.7,
    logo: "M",
    color: "#00A4EF",
    location: "Hyderabad",
    description: "Empower every person and organization to achieve more.",
  },
  {
    id: "infosys",
    name: "Infosys",
    industry: "IT Services",
    openJobs: 120,
    rating: 4.2,
    logo: "I",
    color: "#007CC3",
    location: "Bengaluru",
    description: "Navigate your next with digital transformation.",
  },
  {
    id: "tcs",
    name: "TCS",
    industry: "IT Services",
    openJobs: 210,
    rating: 4.1,
    logo: "T",
    color: "#0B4F8A",
    location: "Mumbai",
    description: "Building on belief through technology and consulting.",
  },
  {
    id: "accenture",
    name: "Accenture",
    industry: "Consulting",
    openJobs: 95,
    rating: 4.3,
    logo: "Ac",
    color: "#A100FF",
    location: "Pune",
    description: "Let there be change — strategy, consulting, digital and operations.",
  },
  {
    id: "wipro",
    name: "Wipro",
    industry: "IT Services",
    openJobs: 88,
    rating: 4.0,
    logo: "W",
    color: "#341C8E",
    location: "Bengaluru",
    description: "Applying thought to deliver technology solutions.",
  },
  {
    id: "ibm",
    name: "IBM",
    industry: "Technology",
    openJobs: 54,
    rating: 4.4,
    logo: "IBM",
    color: "#054ADA",
    location: "Bengaluru",
    description: "Let's create technology that changes the world.",
  },
  {
    id: "deloitte",
    name: "Deloitte",
    industry: "Consulting",
    openJobs: 73,
    rating: 4.5,
    logo: "D",
    color: "#86BC25",
    location: "Gurugram",
    description: "Making an impact that matters for clients and communities.",
  },
  {
    id: "capgemini",
    name: "Capgemini",
    industry: "IT Consulting",
    openJobs: 61,
    rating: 4.2,
    logo: "C",
    color: "#0070AD",
    location: "Mumbai",
    description: "Get the future you want with digital transformation.",
  },
];

export const jobs = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Google",
    companyId: "google",
    location: "Bengaluru, Karnataka",
    salary: { min: 2800000, max: 4500000 },
    experience: "4-7 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "2 days ago",
    skills: ["React", "TypeScript", "Next.js"],
    logo: "G",
    color: "#4285F4",
  },
  {
    id: "2",
    title: "Product Manager",
    company: "Amazon",
    companyId: "amazon",
    location: "Hyderabad, Telangana",
    salary: { min: 3200000, max: 5000000 },
    experience: "5-9 years",
    type: "Full-time",
    mode: "On-site",
    posted: "1 day ago",
    skills: ["Roadmaps", "Analytics", "Agile"],
    logo: "A",
    color: "#FF9900",
  },
  {
    id: "3",
    title: "Cloud Solutions Architect",
    company: "Microsoft",
    companyId: "microsoft",
    location: "Hyderabad, Telangana",
    salary: { min: 3500000, max: 5500000 },
    experience: "6-10 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "3 days ago",
    skills: ["Azure", "DevOps", "Architecture"],
    logo: "M",
    color: "#00A4EF",
  },
  {
    id: "4",
    title: "Java Full Stack Developer",
    company: "Infosys",
    companyId: "infosys",
    location: "Pune, Maharashtra",
    salary: { min: 1200000, max: 2200000 },
    experience: "3-6 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "5 hours ago",
    skills: ["Java", "Spring Boot", "React"],
    logo: "I",
    color: "#007CC3",
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "TCS",
    companyId: "tcs",
    location: "Mumbai, Maharashtra",
    salary: { min: 1500000, max: 2800000 },
    experience: "2-5 years",
    type: "Full-time",
    mode: "Remote",
    posted: "4 days ago",
    skills: ["Python", "ML", "SQL"],
    logo: "T",
    color: "#0B4F8A",
  },
  {
    id: "6",
    title: "UX Design Lead",
    company: "Accenture",
    companyId: "accenture",
    location: "Bengaluru, Karnataka",
    salary: { min: 2000000, max: 3500000 },
    experience: "5-8 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "1 week ago",
    skills: ["Figma", "Research", "Design Systems"],
    logo: "Ac",
    color: "#A100FF",
  },
];

export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    period: "forever",
    description: "Get started with the essentials",
    features: [
      "Basic profile",
      "Limited applications (5/month)",
      "Job alerts",
      "Community access",
    ],
    cta: "Get Started",
    highlighted: false,
    color: "cyan",
  },
  {
    id: "silver",
    name: "Silver",
    price: 499,
    period: "month",
    description: "For active job seekers",
    features: [
      "Unlimited applications",
      "Resume visibility boost",
      "Priority job alerts",
      "Application tracking",
      "Basic resume builder",
    ],
    cta: "Choose Silver",
    highlighted: false,
    color: "blue",
  },
  {
    id: "gold",
    name: "Gold",
    price: 999,
    period: "month",
    description: "Stand out to recruiters",
    features: [
      "Everything in Silver",
      "Priority applications",
      "Resume boost to top",
      "Interview assistance",
      "Mock interview sessions",
      "Salary insights",
    ],
    cta: "Choose Gold",
    highlighted: true,
    color: "orange",
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 1999,
    period: "month",
    description: "Complete career partnership",
    features: [
      "Everything in Gold",
      "Dedicated career support",
      "1:1 career counseling",
      "LinkedIn profile review",
      "Exclusive job invites",
      "Fast-track applications",
    ],
    cta: "Choose Platinum",
    highlighted: false,
    color: "blue",
  },
];

export const howItWorks = [
  { step: 1, title: "Create Account", description: "Sign up in minutes with your email or phone number." },
  { step: 2, title: "Complete Profile", description: "Add your skills, experience, and upload your resume." },
  { step: 3, title: "Choose Membership Plan", description: "Pick a plan that matches your career goals." },
  { step: 4, title: "Browse Jobs", description: "Explore thousands of verified openings across India." },
  { step: 5, title: "Apply to Companies", description: "One-click apply to roles that fit your profile." },
  { step: 6, title: "Get Interview Calls", description: "Connect with recruiters and land your dream job." },
];

export const whyChooseUs = [
  { title: "Verified Companies", description: "Every employer is thoroughly vetted for authenticity." },
  { title: "Safe Platform", description: "Your data is encrypted and never shared without consent." },
  { title: "Fast Hiring", description: "Average time-to-interview under 7 days for active seekers." },
  { title: "Resume Builder", description: "Create ATS-friendly resumes with our smart builder." },
  { title: "Career Guidance", description: "Expert tips and personalized career roadmaps." },
  { title: "Interview Support", description: "Mock interviews and preparation resources included." },
  { title: "24/7 Support", description: "Round-the-clock help whenever you need assistance." },
];

export const testimonials = [
  {
    name: "Priya Sharma",
    role: "Software Engineer at Google",
    avatar: "PS",
    quote:
      "JobCareerPao helped me land my dream role at Google within 3 weeks. The Gold plan's interview assistance was a game changer.",
    rating: 5,
  },
  {
    name: "Rahul Mehta",
    role: "Product Manager at Amazon",
    avatar: "RM",
    quote:
      "The platform's verified companies and clean UI made job hunting feel premium. I received multiple interview calls in days.",
    rating: 5,
  },
  {
    name: "Ananya Patel",
    role: "Data Scientist at Microsoft",
    avatar: "AP",
    quote:
      "From resume boost to dedicated support, Platinum membership accelerated my career switch into AI/ML roles.",
    rating: 5,
  },
  {
    name: "Vikram Singh",
    role: "Full Stack Developer at Infosys",
    avatar: "VS",
    quote:
      "As a fresher, the Free plan got me started, and upgrading to Silver unlocked unlimited applications. Highly recommend!",
    rating: 5,
  },
];

export const blogPosts = [
  {
    slug: "career-tips-2026",
    title: "10 Career Tips to Thrive in 2026",
    category: "Career Tips",
    excerpt: "Actionable advice to future-proof your career in a rapidly evolving job market.",
    date: "Jul 18, 2026",
    readTime: "6 min",
  },
  {
    slug: "ats-resume-guide",
    title: "Build an ATS-Friendly Resume That Gets Noticed",
    category: "Resume Tips",
    excerpt: "Learn how recruiters and ATS systems evaluate resumes — and how to pass both.",
    date: "Jul 14, 2026",
    readTime: "8 min",
  },
  {
    slug: "interview-prep-masterclass",
    title: "Interview Preparation Masterclass",
    category: "Interview Preparation",
    excerpt: "From behavioral rounds to system design — a complete preparation playbook.",
    date: "Jul 10, 2026",
    readTime: "12 min",
  },
  {
    slug: "india-salary-guide-2026",
    title: "India Salary Guide 2026 by Role & City",
    category: "Salary Guide",
    excerpt: "Benchmark your compensation across tech, consulting, and product roles.",
    date: "Jul 5, 2026",
    readTime: "10 min",
  },
  {
    slug: "hiring-trends-india",
    title: "Top Hiring Trends Across Indian Industries",
    category: "Industry News",
    excerpt: "What's hot in hiring: AI roles, hybrid policies, and skills employers want now.",
    date: "Jun 28, 2026",
    readTime: "7 min",
  },
];

export const footerLinks = {
  company: [
    { label: "About", href: "/about" },
    { label: "Careers", href: "/careers" },
    { label: "Contact", href: "/contact" },
  ],
  legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms", href: "/terms" },
    { label: "Refund Policy", href: "/refund" },
  ],
  candidates: [
    { label: "Browse Jobs", href: "/jobs" },
    { label: "Companies", href: "/companies" },
    { label: "Membership Plans", href: "/pricing" },
    { label: "Career Blog", href: "/blog" },
  ],
  recruiters: [
    { label: "Recruiter Portal", href: "/recruiter" },
    { label: "Post a Job", href: "/recruiter/signup" },
    { label: "Recruiter Login", href: "/auth/recruiter/login" },
  ],
};